### ISSUE TITLE
B1 foot ground contact for Low level hardware deployment

### ISSUE THREAD

**Issue by jianwei-liu93** [Ericonaldo/visual_wholebody#12]
I was just wondering how was the foot ground contact detection calculated for deployment of the low level policy on B1? since the Unitree B1 SDK doesn't seem to provide a useable value for foot contact

**Comment by Ericonaldo** [comment]
We use `state.footForce`

**Comment by jianwei-liu93** [comment]
did you use the state.footForce directly from the B1 SDK (i.e. https://github.com/unitreerobotics/unitree_legged_sdk/tree/B1)? if yes, what sort of threshold values did you use for contact/no contact? the state.footForce values we got from the B1 SDK doesn't seem to change very much (remains around 20-28ish), whether the robot is standing or lying down.

**Comment by jianwei-liu93** [comment]
Hi, we spoke to Unitree support and it seems that the `state.footForce` element of the B1 SDK is not actually implemented properly on the hardware. Could it be that the VBC low level policy doesn't actually need the foot contact observation for it to work?

**Comment by Ericonaldo** [comment]
You are right, the obs are actually useless, you can even mask it and will not hurt the performance.

**Comment by jianwei-liu93** [comment]
Ah I see, thank you for confirming

**Comment by heartInsert** [comment]
@jianwei-liu93   Mate , do you  willing to  share  your  deployment   code  ?
