### ISSUE TITLE
Problems with high-level playing

### ISSUE THREAD

**Issue by XiaoWZENG** [Ericonaldo/visual_wholebody#2]
Hi , thanks for your impressive work. 
I encountered some problems when trying to playing the high-level policy. 
Have you ever encountered this before?
Thanks a lot！

raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ActorCritic:
	size mismatch for actor.history_encoder.encoder.0.weight: copying a param with shape torch.Size([30, 71]) from checkpoint, the shape in current model is torch.Size([30, 66]).
	size mismatch for actor.actor_backbone.0.weight: copying a param with shape torch.Size([128, 91]) from checkpoint, the shape in current model is torch.Size([128, 86]).
	size mismatch for critic.critic_backbone.0.weight: copying a param with shape torch.Size([128, 89]) from checkpoint, the shape in current model is torch.Size([128, 84]).

**Comment by Ericonaldo** [comment]
what is your low-level training command and high-level training command?

**Comment by XiaoWZENG** [comment]
The low-level training command is:
python train.py --headless --exptid zzc_0530 --proj_name b1z1-low0530 --task b1z1 --sim_device cuda:0 --rl_device cuda:0 --observe_gait_commands.
and the low-level training policy is work for playing.

The high-level training command is:
python train_multistate.py --rl_device "cuda:0" --sim_device "cuda:0" --timesteps 60000 --headless --task B1Z1PickMulti --experiment_dir b1-pick-multi-teacher --wandb --wandb_project "b1-pick-multi-teacher" --wandb_name "hight level 0530" --roboinfo --observe_gait_commands --small_value_set_zero --rand_control --stop_pick

**Comment by Ericonaldo** [comment]
Are you sure you only have this one low-level policy and the high-level assigns the right path？

**Comment by Ericonaldo** [comment]
missing dimension 5 is obviously a mismatch from observe_gait_commands, check if you are actually using the same arg for both sides.

**Comment by XiaoWZENG** [comment]
Sorry, I had set the wrong file path of the low level policy and added the observe_gait_commands argument. Now it's working. 
Thank you very much for your help. 
Have a nice day.

**Comment by whn981841576** [comment]
> 对不起，我设置了低级别策略的错误文件路径并添加了 observe_gait_commands 参数。现在它正在工作。非常感谢您的帮助。 有好的一天。

how to set observe_gait_commands, i ref walk these way,the observe_gait_commands is true,the same as visual whole body, how to set?
