### ISSUE TITLE
problem of high level

### ISSUE THREAD

**Issue by whn981841576** [Ericonaldo/visual_wholebody#6]
when i run "python train_multistate.py --rl_device "cuda:0" --sim_device "cuda:0" --timesteps 60000 --headless --task B1Z1PickMulti --experiment_dir b1-pick-multi-teacher --wandb --wandb_project "b1-pick-multi-teacher" --wandb_name "some descriptions" --roboinfo --observe_gait_commands --small_value_set_zero --rand_control --stop_pick"
there is a issue 
   " if len(self.gait_indices[suddenstop_indices]) > 0:
IndexError: tensors used as indices must be long, byte or bool tensors"
but when i transform the type of 'suddenstop_indices' from float into long or bool，the training process can be demonstrated in Gym, but when I run "python play_multistate.py"
there still is a issue
RuntimeError: Error(s) in loading state_dict for ActorCritic:
	size mismatch for actor.history_encoder.encoder.0.weight: copying a param with shape torch.Size([30, 71]) from checkpoint, the shape in current model is torch.Size([30, 66]).
	size mismatch for actor.actor_backbone.0.weight: copying a param with shape torch.Size([128, 91]) from checkpoint, the shape in current model is torch.Size([128, 86]).
	size mismatch for critic.critic_backbone.0.weight: copying a param with shape torch.Size([128, 89]) from checkpoint, the shape in current model is torch.Size([128, 84]).

**Comment by heartInsert** [comment]
I meet  the same  problem , have  you solved this problem ? mate.

**Comment by heartInsert** [comment]
I  found  the  right   teacher  high level  play command should  be    `python play_multistate.py --task B1Z1PickMulti --checkpoint "check_point  path"     --roboinfo --observe_gait_commands --small_value_set_zero --rand_control --stop_pick
`
