### ISSUE TITLE
Reward sign

### ISSUE THREAD

**Issue by 42jaylonw** [Ericonaldo/visual_wholebody#9]
For tracking_contacts_shaped_force and tracking_contacts_shaped_vel reward scale, shouldn't they be positive?

https://github.com/Ericonaldo/visual_wholebody/blob/33fc1d90a1b5b10408f6814a020dc32ed4c99d13/low-level/legged_gym/envs/manip_loco/b1z1_config.py#L130

https://github.com/Ericonaldo/visual_wholebody/blob/33fc1d90a1b5b10408f6814a020dc32ed4c99d13/low-level/legged_gym/envs/manip_loco/b1z1_config.py#L131

**Comment by Ericonaldo** [comment]
If you take a close look at the reward function defined in the paper or the code, you will find that there will be less difference in the sign.
![image](https://github.com/user-attachments/assets/dad76a86-47f0-4987-b6f4-498c4d99d17f)
In short, C is a factor in [0,1] that denotes a phase. For our trotting case, that controls when two legs are up or down. For the first reward, it means that, when C is close to zero, encourage the force; for the velocity, vice versa. Therefore, changing the sign only changes the meaning as 'when C is close to zero, penalty the force (when C is close to one, there is less penalty)'. This still helps on learning a phase behavior.

**Comment by 42jaylonw** [comment]
I see, it probably only works when the gait phase can be inverted (50% as a cycle). It would be better to make it positive I think.

**Comment by Ericonaldo** [comment]
You can tune a better one for your own;)
